name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Compile
      run: |
        clojure -Amin
        cp target/public/cljs-out/prod-main.js resources/public/dev-main.js
