name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: DeLaGuardo/setup-clojure@11.0
      with:
        cli: '1.10.1.469'
    - name: Compile
      run: |
        clojure -Amin
        mkdir resources/public/cljs-out
        cp target/public/cljs-out/prod-main.js resources/public/cljs-out/dev-main.js
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.1
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./resources/public
