name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: DeLaGuardo/setup-clojure@2.0
      with:
        tools-deps: '1.10.1.469'
    - name: Compile
      run: |
        clojure -Amin
        cp target/public/cljs-out/prod-main.js resources/public/dev-main.js
